server:
  port: 8002
spring:
  profiles: dev #开发环境
  application:
    name: config-dev1
constant:
  name: xiangjing
  password: '{cipher}38cdb4a6bf22512e80513e0cb7e9ac0dbdfedaf1856543dd0a261389f1752a03'

  
